{
  "swagger": "2.0",
  "info": {
    "title": "API_ID description",
    "description": "Sample API on API Gateway with a Google Cloud Functions backend",
    "version": "1.0.0"
  },
  "schemes": [
    "https"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    "/hello": {
      "get": {
        "summary": "Greet a user",
        "operationId": "hello",
        "x-google-backend": {
          "address": "https://us-central1-qwiklabs-gcp-03-fc640ebad412.cloudfunctions.net/helloGET"
        },
        "security": [
          {
            "api_key": []
          }
        ],
        "responses": {
          "200": {
            "description": "A successful response",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    }
  },
  "securityDefinitions": {
    "api_key": {
      "type": "apiKey",
      "name": "key",
      "in": "query"
    }
  }
}
